In [1]:
import numpy as np

In [2]:
def randomization(n):
    
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    A = np.random.random((n,1))
    return A

In [3]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    A = np.random.random((h,w))
    B = np.random.random((h,w))
    s = np.add(A,B)
    
    return A, B, s

In [4]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    s = np.linalg.norm(np.add(A, B))
    return s

In [5]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    out = np.tanh(np.matmul(weights.T, inputs))
    return out

In [6]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    if x <= y:
        return x*y
    elif y == 0:
        return "division by zero is not valid"
    else:
        return x/y

In [7]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    
    new_vec_fn = np.vectorize(scalar_function)
    return new_vec_fn(x, y)

In [8]:
if __name__ == '__main__':
    print(randomization(8))
    operationA, operationB, operationS = operations(2, 3)
    print(operationA)
    print(operationB)
    print(operationS)
    print(norm(operationA, operationB))
    print(neural_network(operationA, operationB))
    print(scalar_function(5, 6))
    print(vector_function(operationA, operationB))

[[0.86180566]
 [0.5953453 ]
 [0.92085129]
 [0.23843432]
 [0.30362865]
 [0.51728232]
 [0.58079743]
 [0.06755597]]
[[0.51613235 0.13063064 0.27305862]
 [0.9103062  0.79955914 0.96806391]]
[[0.57365411 0.5047496  0.43622064]
 [0.56836908 0.13306497 0.44273327]]
[[1.08978645 0.63538023 0.70927926]
 [1.47867527 0.9326241  1.41079718]]
2.672271802156334
[[0.67150077 0.48490816 0.60870328]
 [0.36413733 0.17064319 0.2604971 ]
 [0.55679112 0.38930041 0.49880036]]
30
[[0.29608144 0.06593576 0.11911381]
 [1.60161105 6.0087878  2.18656239]]
